### PR TITLE
Re-merge SF and GH versions

### PR DESCRIPTION
**Pull request by ghost**
SourceForge has a later version of Trebuchet, but I made some changes to the GitHub version of Trebuchet recently.
These diffs manually merge them back together.

TODO:
bump up to a new version number
then, after making a new version number, make a release on both SourceForge and GitHub, and also update the code tree on SourceForge
alternatively: stop using SF if it's difficult to keep SF and GH in sync, and change all the sourceforge links to github links

@revarbat what do you think is the best option?

### CODE REVIEW

**Comment by ghost** [comment]
This mostly solves:
https://github.com/revarbat/trebuchet/issues/1

**Comment by revarbat** [comment]
To be honest, I've no real interest in maintaining this myself anymore.  Want to take project ownership, @nyanster ?

**Comment by ghost** [comment]
> To be honest, I've no real interest in maintaining this myself anymore. Want to take project ownership, @nyanster ?

I don't know Tcl, though. :B  (thus, none of my fixes so far have been anything other than non-Tcl housekeeping)

@wyld-sw , do you think Trebuchet is something that could be put into the @fuzzball-muck account?  A lot of Trebuchet-related links already redirect to fuzzball.org anyway, so I think it'd be an alright home for it!

Also, @revarbat , if you're uninterested in maintaining it, may I ask if you'd be willing to re-license your code from GPL to MIT (or BSD 2-clause) before it (Trebuchet/Trebuchet's repo) gets transferred to another account?  No pressure though, if you'd rather not!  (and I know there's been a couple other authors like Henri and Points who might need to be asked for permission to re-license, too)

**Comment by wyld-sw** [comment]
I would be fine with it being stored under fuzzball-muck. Let me know what content needs to be reestablished on fuzzball.org if the time comes, too.

**Comment by ghost** [comment]
> I would be fine with it being stored under fuzzball-muck. Let me know what content needs to be reestablished on fuzzball.org if the time comes, too.

:D

If @revarbat has a backup of belfry.com's /fuzzball/ directory, that'd be really useful!  Right now a lot of stuff that used to be there is only visible by using http://web.archive.org/

**Comment by ghost** [comment]
https://help.github.com/en/articles/transferring-a-repository

**Comment by ghost** [comment]
Moving some of this discussion here:
https://github.com/revarbat/trebuchet/issues/4

**Pull request merged**
